const CaseStudy = {
  items: [
    {
      name: "Annexa",
      id: 1,
      product: "Product Design, UI/UX",
      image: "/assets/home/section-six/annexa.svg",
      backgroundColor: "#234085",
      textColor: "#fff",
      secondname: "Docxna",
      secondid: 2,
      secondproduct: "Product Design, UI/UX",
      secondimage: "/assets/home/section-six/docxna.svg",
      secondbackgroundColor: "#D1E1E1",
      secondtextColor: "#fff",
      inverted: false,
    },
    {
      name: "Hire Me",
      id: 3,
      product: "Product Design, UI/UX",
      image: "/assets/home/section-six/hire.svg",
      backgroundColor: "#01DBF0",
      textColor: "#fff",
      secondname: "Danco",
      secondid: 4,
      secondproduct: "Product Design, UI/UX",
      secondimage: "/assets/home/section-six/danco.svg",
      secondbackgroundColor: "#796AF2",
      secondtextColor: "#fff",
      inverted: true,
    },
    {
      name: "Telescope",
      id: 5,
      product: "Product Design, UI/UX",
      image: "/assets/home/section-six/telescope.svg",
      backgroundColor: "#FF5E95",
      textColor: "#fff",
      secondname: "Hire Me",
      secondid: 6,
      secondproduct: "Product Design, UI/UX",
      secondimage: "/assets/home/section-six/hire_green.svg",
      secondbackgroundColor: "#00601B",
      secondtextColor: "#fff",
      inverted: false,
    },
    {
      name: "Docxna",
      id: 7,
      product: "Product Design, UI/UX",
      image: "/assets/home/section-six/docxna_grey.svg",
      backgroundColor: "#505252",
      textColor: "#fff",
      secondname: "Add your own project",
      secondid: 8,
      inverted: true,
    },
  ],
};

export default CaseStudy;
